# Generated by Django 2.0.1 on 2018-01-14 13:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(default='Unknown', max_length=20)),
                ('first_name', models.CharField(default='Unknown', max_length=20)),
                ('last_name', models.CharField(default='Unknown', max_length=20)),
                ('email', models.EmailField(max_length=254, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Freelance', max_length=20)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rest_framework_test_app.Company')),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hired', models.DateTimeField(auto_now_add=True)),
                ('first_name', models.CharField(default='Unknown', max_length=20)),
                ('last_name', models.CharField(default='Unknown', max_length=20)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('rate', models.FloatField(default=0.0)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rest_framework_test_app.Department')),
            ],
        ),
    ]
